---
language: python

python:
  - 3.5
  - 3.6
  - 3.7

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install flake8 pylint

script:
  - flake8 github_repo_management/
  - pylint github_repo_management/
